# Generated by Django 5.0.1 on 2024-02-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review_table',
        ),
    ]
