# Generated by Django 5.0.1 on 2024-01-19 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customeruser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami quyidagi formatda kiritilishi kerak: '+998XXXXXXXXX'.", regex='^\\+998\\d{9}$')]),
        ),
    ]
